---
## FIXME! add support if googlesanta installed and in Lockdown mode... must switch to monitor during upgrade

## FIXME! not supported
# - name: Darwin | macports upgrade
#   macports: name=* present=latest
#   when: ansible_os_family == "Darwin"
- name: Darwin | macports port selfupdate dryrun
  command: "/opt/local/bin/port -yv selfupdate --nosync"
  register: darwinmpsu0
  changed_when: false
  ignore_errors: true
  async: 1800
  poll: 180
- name: Debug | var darwinmpsu0
  debug: var=darwinmpsu0
  when: (verbose is defined and verbose)

- block:
    - name: Google Santa | ensure config set to monitor mode
      osx_defaults:
        domain: /var/db/santa/config.plist
        key: ClientMode
        value: 0
        type: "{{ harden_darwin_santa_db_type }}"
      when: >
        (harden_darwin_santa_mode == 'LOCKDOWN' or harden_darwin_santa_mode == 2) and
        upgradepkgs_darwin_santa_temporary_monitor

    - name: Darwin | macports port selfupdate
      command: "/opt/local/bin/port selfupdate"
      register: darwinmpsu
    - name: Debug | var darwinmpsu
      debug: var=darwinmpsu
      when: (verbose is defined and verbose)
    - name: set darwin_updated var
      set_fact:
        darwin_updated: true
        upgrade_need_hidsupdate: true
  when: (darwinmpsu0.stdout.find("MacPorts base is already the latest version") == -1)
  always:
    - name: Google Santa | ensure config set to lockdown mode
      osx_defaults:
        domain: /var/db/santa/config.plist
        key: ClientMode
        value: "{{ harden_darwin_santa_mode }}"
        type: "{{ harden_darwin_santa_db_type }}"
      when: >
        (harden_darwin_santa_mode == 'LOCKDOWN' or harden_darwin_santa_mode == 2) and
        upgradepkgs_darwin_santa_temporary_monitor

## No option to do a dryrun sync
- name: Darwin | macports sync
  command: "/opt/local/bin/port sync"
  failed_when: false
  changed_when: true

- name: Darwin | check for outdated macports
  command: "/opt/local/bin/port outdated"
  register: darwinmp
  ignore_errors: true
  changed_when: false
- name: Debug | var darwinmp
  debug: var=darwinmp
  when: (verbose is defined and verbose)
- block:
    - name: Google Santa | ensure config set to monitor mode
      osx_defaults:
        domain: /var/db/santa/config.plist
        key: ClientMode
        value: 0
        type: "{{ harden_darwin_santa_db_type }}"
      when: >
        (harden_darwin_santa_mode == 'LOCKDOWN' or harden_darwin_santa_mode == 2) and
        upgradepkgs_darwin_santa_temporary_monitor

    - name: Darwin | macports port outdated upgrade
      command: "/opt/local/bin/port upgrade outdated "
      register: darwinmp2
    - name: set darwin_updated var
      set_fact:
        darwin_updated: true
        upgrade_need_hidsupdate: true
  when: not ("No installed ports are outdated." in darwinmp.stdout)
  always:
    - name: Google Santa | ensure config set to lockdown mode
      osx_defaults:
        domain: /var/db/santa/config.plist
        key: ClientMode
        value: "{{ harden_darwin_santa_mode }}"
        type: "{{ harden_darwin_santa_db_type }}"
      when: >
        (harden_darwin_santa_mode == 'LOCKDOWN' or harden_darwin_santa_mode == 2) and
        upgradepkgs_darwin_santa_temporary_monitor
## FIXME! need to regenerate hash whitelist for updated ports...

- name: Darwin | check for inactive macports
  command: "/opt/local/bin/port installed inactive"
  register: darwinmpi
  ignore_errors: true
  changed_when: false

- name: Debug | var darwinmpi
  debug: var=darwinmpi
  when: (verbose is defined and verbose)
## FIXME! to still allow rollback, would need an inactive minus 1/n back
- block:
    - name: Darwin | macports uninstall inactive
      command: "/opt/local/bin/port uninstall inactive"
      register: darwinmpi2
      ignore_errors: true
    - name: set darwin_updated var
      set_fact:
        darwin_updated: true
        upgrade_need_hidsupdate: true
  when: >
    darwinmpi.stderr is defined and
    darwinmpi.stderr.find("None of the specified ports are installed.") == -1 and
    upgradepkgs_darwinmp_remove_inactive

## FIXME! port uninstall leaves (~autoremove?)
