---

## OpenBSD 6.1/amd64: syspatch can be used to apply binary updates, https://www.openbsd.org/errata61.html

- name: OpenBSD | upgrade all packages  # noqa package-latest
  community.general.openbsd_pkg:
    name: '*'
    state: latest
  tags:
    - upgrade
  async: 3600
  poll: 180
  register: pkg_result
  until: pkg_result is success
