---

- name: lxc containers | restart from host
  debug: msg="You will need to reboot system. restart from container host."
  when: ansible_virtualization_type == 'lxc'

- name: Need to reboot system but asked not
  debug: msg="You will need to reboot system. asked ansible not doing it."
  when: noreboot is defined and noreboot[inventory_hostname]

# - debug: var="{{ not (noreboot is defined and noreboot[inventory_hostname] is defined and
#               noreboot[inventory_hostname]) and ansible_virtualization_type != 'lxc' }}"
- block:
    - name: Reboot system
      reboot:
        reboot_timeout: 300
  when: >
    not (noreboot is defined and noreboot[inventory_hostname] is defined and noreboot[inventory_hostname]) and
    ansible_virtualization_type != 'lxc'
