---

- name: Redhat | upgrade all packages
  ansible.builtin.package:  # noqa package-latest
    name: '*'
    state: latest
    update_cache: yes
    skip_broken: "{{ upgrade_rhel_skip_broken | default('no') }}"
    security: "{{ upgrade_rhel_security_only | default('no') }}"
  tags:
    - upgrade
  async: 3600
  poll: 180
  register: yumu
  until: yumu is success

- name: Need HIDS update
  ansible.builtin.set_fact:  # noqa no-handler
    upgrade_need_hidsupdate: true
  when: yumu.changed

## no marker on redhat
## http://serverfault.com/questions/671863/need-to-check-whether-you-need-to-reboot-for-a-kernel-update
## http://stackoverflow.com/questions/22597424/ansible-detect-changes-in-certain-files-after-yum-update-and-do-a-reboot
- name: Check for reboot hint.
  ansible.builtin.shell: >
    if [ "`rpm -q kernel --queryformat '%{installtime} %{version}-%{release}.%{arch}\n' |
        sort -n -k1 | tail -1 | cut -d ' ' -f 2`" = "`uname -r`" ]; then
        echo "no"; else echo "reboot";
    fi
  ignore_errors: true
  register: reboot_hint
  changed_when: false
- name: redhat | flag system for reboot
  ansible.builtin.set_fact:
    upgrade_need_reboot: true
  when: reboot_hint.stdout.find("reboot") != -1
