---

#    - debug: var=packages
## Note: if doing host, might be blocking
    - name: Do we have a virtualbox package update?
      set_fact:
        virtualbox_host: true
      when: >
        ansible_system == "Linux" and
        packages is defined and packages.stdout is defined and
        packages.stdout.find("virtualbox-") != -1

    - fail: msg="Warning! update includes virtualbox..."
      when: virtualbox_host is defined and virtualbox_host

#    - debug: var=file

    ## not needed if reboot
    #- name: relink libraries
    #  command: /sbin/ldconfig

    # or just halt ?

#   - name: wait for the server to finish rebooting
#     local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300

    - name: waiting for server to come back
      wait_for: host={{ inventory_hostname }} state=started
      delegate_to: localhost
      become: false
#      when: file.stat.exists is defined and file.stat.exists == true and not noreboot
      when: >
        (file.stat.exists is defined and file.stat.exists == true and
          (not noreboot or noreboot[inventory_hostname] is not defined)
        ) or
        (ansible_os_family == "Darwin" and
          (darwinsu2.stdout is defined and darwinsu2.stdout.find("Please restart immediately") != -1)
        )
