---

## Virtualbox guest additions?
## https://github.com/BTBurke/skeleton-vagrant-ansible/blob/master/provisioning/vboxadditions.yaml

- name: host | check if Virtualbox installed
  stat: path=/usr/bin/virtualbox
  delegate_to: localhost
  register: localvbox
  become: no
- name: Find Host Virtualbox Version
  become: no
  shell: |
    set -o pipefail
    virtualbox -h | awk '/Oracle VM VirtualBox Manager/ {split($0,a," "); print a[5]}'
  args:
    executable: /bin/bash
  delegate_to: localhost
  register: hostV
  when: localvbox.stat.exists
  changed_when: False

- name: Find Guest Additions Version
  shell: |
    set -o pipefail
    modinfo vboxguest | awk '/^version:/ { print $2 }'
  args:
    executable: /bin/bash
  register: guestV
  changed_when: False

- name: Debug | var hostV
  debug: var=hostV
  when: (verbose is defined and verbose)
- name: Debug | var guestV
  debug: var=guestV
  when: (verbose is defined and verbose)
- name: Check if /vagrant path is present
  stat: path=/vagrant
  register: vagrantdir
- name: virtualbox guest - vagrant
  set_fact:
    isodir: /vagrant/{{ hostV.stdout }}
  when: vagrantdir.stat.exists
- name: virtualbox guest - generic box
  set_fact:
    isodir: /tmp/{{ hostV.stdout }}
  when: not vagrantdir.stat.exists
- name: Check if Guest Additions iso is present
  stat: path="/{{ isodir }}/VBoxGuestAdditions_{{ hostV.stdout }}.iso"
  register: vboxguestadditions
  when: hostV.stdout is defined
- name: Download Guest Additions Installer (when required)
  get_url:
    dest: "{{ isodir }}"
    url: "http://download.virtualbox.org/virtualbox/{{ hostV.stdout }}/VBoxGuestAdditions_{{ hostV.stdout }}.iso"
    mode: '0644'
  when: >
    hostV is defined and hostV.stdout and guestV is defined and guestV.stdout and
    hostV.stdout != guestV.stdout and not vboxguestadditions.stat.exists

- name: Check if VBoxGuestAdditions iso is present
  stat:
    path: "{{ isodir }}/VBoxGuestAdditions_{{ hostV.stdout }}.iso"
  register: vboxguestadditions
  when: hostV.stdout is defined
- name: Mount Guest Additions .iso (when required)
  mount:
    name: /mnt
    src: "/{{ isodir }}/VBoxGuestAdditions_{{ hostV.stdout }}.iso"
    opts: loop,ro
    fstype: iso9660
    state: mounted
  when: >
    hostV is defined and hostV.stdout and guestV is defined and guestV.stdout and
    hostV.stdout != guestV.stdout and vboxguestadditions.stat.exists

## as role/harden protection
- name: Check if harden apt 99security is present
  stat: path=/etc/apt/apt.conf.d/99security
  register: hardenapt
- name: remove immutable tag from /lib directory
  file:
    path: /lib
    state: directory
    recurse: yes
    attr: -i
  when: >
    hardenapt.stat.exists and
    ((hostV is defined and hostV.stdout and guestV is defined and guestV.stdout and
      hostV.stdout != guestV.stdout) or
      (virtualbox_host is defined and virtualbox_host)
    )
- name: Install Guest Additions (when required)
  command: /mnt/VBoxLinuxAdditions.run --nox11 -- --force
  when: >
    hostV is defined and hostV.stdout and guestV is defined and guestV.stdout and
    hostV.stdout != guestV.stdout
  become: yes
  failed_when: false  # Need to ignore errors here because no windowing system is installed on server image.  No way to override.
- name: Ensure virtualbox module is build for latest kernel
  command: /sbin/rcvboxdrv setup
  become: yes
  when: virtualbox_host is defined and virtualbox_host
- name: set immutable tag from /lib directory
  file:
    path: /lib
    state: directory
    recurse: yes
    attr: +i
  when: >
    hardenapt.stat.exists and
    ((hostV is defined and hostV.stdout and guestV is defined and
      guestV.stdout and hostV.stdout != guestV.stdout) or
      (virtualbox_host is defined and virtualbox_host)
    )

    #    - name: Halting the VM since Guest Additions Updated
    #      local_action: command vagrant halt
    #      become: no
    #      when: hostV.stdout != guestV.stdout

    #    - name: Restarting the VM without provisioning
    #      local_action: command vagrant up --no-provision
    #      become: no
    #      when: hostV.stdout != guestV.stdout

- name: apt | Mark VM for reboot since Guest Additions Updated
  file:
    path: /var/run/reboot-required
    state: touch
    mode: '0644'
  when: >
    (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and
    hostV is defined and hostV.stdout and
    guestV.stdout and hostV.stdout != guestV.stdout
