---

## Virtualbox guest additions?
## https://github.com/BTBurke/skeleton-vagrant-ansible/blob/master/provisioning/vboxadditions.yaml

- name: Host | check if Virtualbox installed
  ansible.builtin.stat: path=/usr/bin/virtualbox
  delegate_to: localhost
  register: localvbox
  become: no
- name: Find Host Virtualbox Version
  become: no
  ansible.builtin.shell: |
    set -o pipefail
    virtualbox -h | awk '/Oracle VM VirtualBox Manager/ {split($0,a," "); print a[5]}'
  args:
    executable: /bin/bash
  delegate_to: localhost
  register: host_v
  when: localvbox.stat.exists
  changed_when: False

- name: Find Guest Additions Version
  ansible.builtin.shell: |
    set -o pipefail
    modinfo vboxguest | awk '/^version:/ { print $2 }'
  args:
    executable: /bin/bash
  register: guest_v
  changed_when: False

- name: Debug | var host_v
  ansible.builtin.debug: var=host_v
  when: (verbose is defined and verbose)
- name: Debug | var guest_v
  ansible.builtin.debug: var=guest_v
  when: (verbose is defined and verbose)
- name: Check if /vagrant path is present
  ansible.builtin.stat: path=/vagrant
  register: vagrantdir
- name: Virtualbox guest - vagrant
  ansible.builtin.set_fact:
    isodir: /vagrant/{{ host_v.stdout }}
  when: vagrantdir.stat.exists
- name: Virtualbox guest - generic box
  ansible.builtin.set_fact:
    isodir: /tmp/{{ host_v.stdout }}
  when: not vagrantdir.stat.exists
- name: Check if Guest Additions iso is present
  ansible.builtin.stat: path="/{{ isodir }}/VBoxGuestAdditions_{{ host_v.stdout }}.iso"
  register: vboxguestadditions
  when: host_v.stdout is defined
- name: Download Guest Additions Installer (when required)
  ansible.builtin.get_url:
    dest: "{{ isodir }}"
    url: "http://download.virtualbox.org/virtualbox/{{ host_v.stdout }}/VBoxGuestAdditions_{{ host_v.stdout }}.iso"
    mode: '0644'
  when: >
    host_v is defined and host_v.stdout and guest_v is defined and guest_v.stdout and
    host_v.stdout != guest_v.stdout and not vboxguestadditions.stat.exists

- name: Check if VBoxGuestAdditions iso is present
  ansible.builtin.stat:
    path: "{{ isodir }}/VBoxGuestAdditions_{{ host_v.stdout }}.iso"
  register: vboxguestadditions
  when: host_v.stdout is defined
- name: Mount Guest Additions .iso (when required)
  mount:
    name: /mnt
    src: "/{{ isodir }}/VBoxGuestAdditions_{{ host_v.stdout }}.iso"
    opts: loop,ro
    fstype: iso9660
    state: mounted
  when: >
    host_v is defined and host_v.stdout and guest_v is defined and guest_v.stdout and
    host_v.stdout != guest_v.stdout and vboxguestadditions.stat.exists

## as role/harden protection
- name: Check if harden apt 99security is present
  ansible.builtin.stat: path=/etc/apt/apt.conf.d/99security
  register: hardenapt
- name: Remove immutable tag from /lib directory
  ansible.builtin.file:
    path: /lib
    state: directory
    recurse: yes
    attr: -i
  when: >
    hardenapt.stat.exists and
    ((host_v is defined and host_v.stdout and guest_v is defined and guest_v.stdout and
      host_v.stdout != guest_v.stdout) or
      (virtualbox_host is defined and virtualbox_host)
    )
- name: Install Guest Additions (when required)
  ansible.builtin.command: /mnt/VBoxLinuxAdditions.run --nox11 -- --force
  when: >
    host_v is defined and host_v.stdout and guest_v is defined and guest_v.stdout and
    host_v.stdout != guest_v.stdout
  become: yes
  failed_when: false  # Need to ignore errors here because no windowing system is installed on server image.  No way to override.
- name: Ensure virtualbox module is build for latest kernel
  ansible.builtin.command: /sbin/rcvboxdrv setup
  become: yes
  when: virtualbox_host is defined and virtualbox_host
- name: Set immutable tag from /lib directory
  ansible.builtin.file:
    path: /lib
    state: directory
    recurse: yes
    attr: +i
  when: >
    hardenapt.stat.exists and
    ((host_v is defined and host_v.stdout and guest_v is defined and
      guest_v.stdout and host_v.stdout != guest_v.stdout) or
      (virtualbox_host is defined and virtualbox_host)
    )

- name: Debian | Mark VM for reboot since Guest Additions Updated
  ansible.builtin.file:
    path: /var/run/reboot-required
    state: touch
    mode: '0644'
  when: >
    (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and
    host_v is defined and host_v.stdout and
    guest_v.stdout and host_v.stdout != guest_v.stdout
